let songsArray = [
  {
    name: "Puppets",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:18",
    plays: "8,026,989",
  },
  {
    name: "Heavy",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:00",
    plays: "4,426,469",
  },
  {
    name: "2z Don Corleon",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:18",
    plays: "33,579,096",
  },
  {
    name: "R.I.P Uncle Holas",
    creator: "Lil 2z, Trapboy Freddy",
    albumCover: "../images/6AM album cover.png",
    timeLength: "1:59",
    plays: "1,049,511",
  },
  {
    name: "On my own",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:08",
    plays: "8,476,750",
  },
  {
    name: "Deep end",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:10",
    plays: "630,488",
  },
  {
    name: "Ceremony",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:10",
    plays: "627,260",
  },
  {
    name: "Vacation",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:09",
    plays: "566,728",
  },
  {
    name: "Live Slow, Die Fast",
    creator: "Lil 2z, Jayski",
    albumCover: "../images/6AM album cover.png",
    timeLength: "3:26",
    plays: "830,100",
  },
  {
    name: "Better off",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:48",
    plays: "780,803",
  },
  {
    name: "Jurassic",
    creator: "Lil 2z",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2:21",
    plays: "707,083",
  },
  {
    name: "Saving Grace",
    creator: "Lil 2z, Jayski",
    albumCover: "../images/6AM album cover.png",
    timeLength: "3:33",
    plays: "483,763",
  },
  {
    name: "Tell us Apart",
    creator: "Lil 2z, Jayski",
    albumCover: "../images/6AM album cover.png",
    timeLength: "2,21",
    plays: "956,542",
  },
  {
    name: "Misunderstood",
    creator: "Lil 2z, Jayski",
    albumCover: "../images/6AM album cover.png",
    timeLength: "1:58",
    plays: "480,671",
  },
];

export default songsArray;
