let songsArray = [
  {
    name: "Nikes",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "5:14",
    plays: "286,482,327",
  },
  {
    name: "Ivy",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "4:09",
    plays: "645,358,327",
  },
  {
    name: "Pink + White",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "3:04",
    plays: "941,989,830",
  },
  {
    name: "Be Yourself",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "1:26",
    plays: "68,001,989",
  },
  {
    name: "Solo",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "4:17",
    plays: "199,481,515",
  },
  {
    name: "Skyline To",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "3:04",
    plays: "95,076,123",
  },
  {
    name: "Self Controle",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "4:09",
    plays: "377,444,024",
  },
  {
    name: "Good Guy",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "1:09",
    plays: "88,658,636",
  },
  {
    name: "Nights",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "5:07",
    plays: "627,564,919",
  },
  {
    name: "Solo(Reprise)",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "1:18",
    plays: "72,559,361",
  },
  {
    name: "Pretty Sweet",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "2:38",
    plays: "61,437,675",
  },
  {
    name: "Facebook Story",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "1:08",
    plays: "48,486,981",
  },
  {
    name: "Close To You",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "1:25",
    plays: "90,183,754",
  },
  {
    name: "White Ferrari",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "4:08",
    plays: "397,691,592",
  },
  {
    name: "Seigried",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "5:34",
    plays: "131,596,380",
  },
  {
    name: "Godspeed",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "2:57",
    plays: "315,238,932",
  },
  {
    name: "Futura Free",
    creator: "Frank Ocean",
    albumCover: "../images/blond album cover.png",
    timeLength: "9:24",
    plays: "71,904,763",
  },
];

export default songsArray;
