let songsArray = [
  {
    name: "Sherane a.k.a Master Splinter's Daughter",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "4:33",
    plays: "64,358,119",
    link: "https://open.spotify.com/track/3KHjXNQDEZ0Hb2hzGdxcx7?si=05f93ad489e947e7",
  },
  {
    name: "Bitch, Don't Kill My Vibe",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:10",
    plays: "639,274,527",
    link: "https://open.spotify.com/track/0yhMmqax6HRAZxI7udEask?si=a52f8401bb9d4873",
  },
  {
    name: "Backseat Freestyle",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "3:32",
    plays: "378,854,770",
    link: "https://open.spotify.com/track/0vjKXtFLt6Ti08Y3JCnRKB?si=39bc96b3c7fd4f6c",
  },
  {
    name: "The Art of Peer Pressure",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:24",
    plays: "108,336,550",
    link: "https://open.spotify.com/track/4Gf6VlNy2E4VVuAkl0y2XW?si=2aea07dd146b4c2e",
  },
  {
    name: "Money Trees",
    creator: "Kendrick Lamar, Jay Rock",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "6:26",
    plays: "1,214,889,701",
    link: "https://open.spotify.com/track/74tLlkN3rgVzRqQJgPfink?si=d8663711b70f4ade",
  },
  {
    name: "Poetic Justice",
    creator: "Kendrick Lamar, Drake",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:00",
    plays: "464,537,958",
    link: "https://open.spotify.com/track/5J6CXHvsfRGyyCnQZmVPoE?si=8ee794223ca34f24",
  },
  {
    name: "good kid",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "3:34",
    plays: "85,488,242",
    link: "https://open.spotify.com/track/3yapR7DctB2WtbmXkHHviC?si=0c8f8ab9acbb484f",
  },
  {
    name: "m.A.A.dd city",
    creator: "Kendrick Lamar, MC Eiht",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:50",
    plays: "676,876,772",
    link: "https://open.spotify.com/track/0nfQguNoAfKFjsQHr6qnxc?si=deb7998b97c0402d",
  },
  {
    name: "Swimming Pools(Drank)- Extended Version",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:14",
    plays: "410,953,992",
    link: "https://open.spotify.com/track/3VYzbU22BooAROigHHwycs?si=4b02b2c133d74dc5",
  },
  {
    name: "Sing About Me, I'm Dying Of Thirst",
    creator: "Kendrick Lamar",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "12:03",
    plays: "150,738,301",
    link: "https://open.spotify.com/track/69pkT3GewmjhQf6vQWcK2L?si=c1015bf265c049b8",
  },
  {
    name: "Real",
    creator: "Kendrick Lamar, Anna Wise",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "7:23",
    plays: "68,789,640",
    link: "https://open.spotify.com/track/2MYm1yy4bYba3mGF9Ou6Yo?si=6b187e3550004450",
  },
  {
    name: "Compton",
    creator: "Kendrick Lamar, Dr. Dre",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "4:08",
    plays: "74,968,239",
    link: "https://open.spotify.com/track/3i2XxFTLd2061UISvE5W7f?si=484ad13a4db746d7",
  },
  {
    name: "Bitch, Don't Kill My Vibe - Remix",
    creator: "Kendrick Lamar, JAY-Z",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "4:38",
    plays: "127,612,337",
    link: "https://open.spotify.com/track/3SImXx6qmobDK2q7MKeR1Z?si=73f31c996b9f433a",
  },
  {
    name: "Bitch, Dont Kill My Vibe - International ...",
    creator: "Kendrick Lamar, Emeli Sande",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:05",
    plays: "639,274,527",
    link: "https://open.spotify.com/track/6WfA83OCEsiZ2IOTbUF4UQ?si=c92cca6137af49c4",
  },
];

export default songsArray;
