let songsArray = [
    {
      name: "Sherane a.k.a Master Splinter's Daughter",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "4:33",
      plays: "64,358,119",
    },
    {
      name: "Bitch, Don't Kill My Vibe",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:10",
      plays: "639,274,527",
    },
    {
      name: "Backseat Freestyle",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "3:32",
      plays: "378,854,770",
    },
    {
      name: "The Art of Peer Pressure",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:24",
      plays: "108,336,550",
    },
    {
      name: "Money Trees",
      creator: "Kendrick Lamar, Jay Rock",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "6:26",
      plays: "1,214,889,701",
    },
    {
      name: "Poetic Justice",
      creator: "Kendrick Lamar, Drake",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:00",
      plays: "464,537,958",
    },
    {
      name: "good kid",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "3:34",
      plays: "85,488,242",
    },
    {
      name: "m.A.A.dd city",
      creator: "Kendrick Lamar, MC Eiht",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:50",
      plays: "676,876,772",
    },
    {
      name: "Swimming Pools(Drank)- Extended Version",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:14",
      plays: "410,953,992",
    },
    {
      name: "Sing About Me, I'm Dying Of Thirst",
      creator: "Kendrick Lamar",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "12:03",
      plays: "150,738,301",
    },
    {
      name: "Real",
      creator: "Kendrick Lamar, Anna Wise",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "7:23",
      plays: "68,789,640",
    },
    {
      name: "Compton",
      creator: "Kendrick Lamar, Dr. Dre",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "4:08",
      plays: "74,968,239",
    },
    {
      name: "Bitch, Don't Kill My Vibe - Remix",
      creator: "Kendrick Lamar, JAY-Z",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "4:38",
      plays: "127,612,337",
    },
    {
      name: "Bitch, Dont Kill My Vibe - International ...",
      creator: "Kendrick Lamar, Emeli Sande",
      albumCover: "../images/good kid maad city album cover.png",
      timeLength: "5:05",
      plays: "639,274,527",
    },
  ];
  
export default songsArray;
  