let songsArray = [
    {
      name: "Good Morning",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:15",
      plays: "260,467,914",
    },
    {
      name: "Champion",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "2:47",
      plays: "174,005,445",
    },
    {
      name: "Stronger",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "5:11",
      plays: "1,265,442,459",
    },
    {
      name: "I Wonder",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "4:03",
      plays: "510,769,070",
    },
    {
      name: "Good Life",
      creator: "Kanye West. T-pain",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:27",
      plays: "366,658,045",
    },
    {
      name: "Cant Tell Me Nothing",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "4:31",
      plays: "456,869,226",
    },
    {
      name: "Barry Bonds",
      creator: "Kanye West, Lil Wayne",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:24",
      plays: "53,839,658",
    },
    {
      name: "Drunk and Hot Girls",
      creator: "Kanye West, Mos Def",
      albumCover: "../images/graduation album cover.png",
      timeLength: "5:13",
      plays: "47,553,218", 
    },
    {
      name: "Flashing Lights",
      creator: "Kanye West, Dwele",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:57",
      plays: "797,264,218",
    },
    {
      name: "Everything I Am",
      creator: "Kanye West, DJ Premiere",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:47",
      plays: "167,507,640",
    },
    {
      name: "The Glory",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:32",
      plays: "70,242,685",
    },
    {
      name: "Homecoming",
      creator: "Kanye West, Chris Martin",
      albumCover: "../images/graduation album cover.png",
      timeLength: "2:18",
      plays: "8,026,989",
    },
    {
      name: "Big Brother",
      creator: "Kanye West",
      albumCover: "../images/graduation album cover.png",
      timeLength: "4:47",
      plays: "55,413,052",
    },
    {
      name: "Good Night",
      creator: "Kanye West, Mos Def, Albe Back",
      albumCover: "../images/graduation album cover.png",
      timeLength: "3:05",
      plays: "23,913,843",
    },
  ];
  
export default songsArray;
  