let songsArray = [
  {
    name: "Good Morning",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:15",
    plays: "260,467,914",
    link: "https://open.spotify.com/track/6MXXY2eiWkpDCezVCc0cMH?si=a8b439b4c18d474e",
  },
  {
    name: "Champion",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "2:47",
    plays: "174,005,445",
    link: "https://open.spotify.com/track/4UQMOPSUVJVicIQzjAcRRZ?si=4d7fc9e937744b9e",
  },
  {
    name: "Stronger",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "5:11",
    plays: "1,265,442,459",
    link: "https://open.spotify.com/track/0j2T0R9dR9qdJYsB7ciXhf?si=53a5f72cb5f346d2",
  },
  {
    name: "I Wonder",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "4:03",
    plays: "510,769,070",
    link: "https://open.spotify.com/track/7rbECVPkY5UODxoOUVKZnA?si=8f05b81009634930",
  },
  {
    name: "Good Life",
    creator: "Kanye West. T-pain",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:27",
    plays: "366,658,045",
    link: "https://open.spotify.com/track/4ZPdLEztrlZqbJkgHNw54L?si=41118f6192324405",
  },
  {
    name: "Cant Tell Me Nothing",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "4:31",
    plays: "456,869,226",
    link: "https://open.spotify.com/track/0mEdbdeRFQwBhN4xfyIeUM?si=5cecab869c6444f4",
  },
  {
    name: "Barry Bonds",
    creator: "Kanye West, Lil Wayne",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:24",
    plays: "53,839,658",
    link: "https://open.spotify.com/track/7387VaiHpOsSIZ5nmjseya?si=35745225bb6d4818",
  },
  {
    name: "Drunk and Hot Girls",
    creator: "Kanye West, Mos Def",
    albumCover: "../images/graduation album cover.png",
    timeLength: "5:13",
    plays: "47,553,218",
    link: "https://open.spotify.com/track/7DRuzSlhjKadgdsQRYZ0tr?si=772f2218054742b7",
  },
  {
    name: "Flashing Lights",
    creator: "Kanye West, Dwele",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:57",
    plays: "797,264,218",
    link: "https://open.spotify.com/track/5TRPicyLGbAF2LGBFbHGvO?si=5080d40d4c254ca9",
  },
  {
    name: "Everything I Am",
    creator: "Kanye West, DJ Premiere",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:47",
    plays: "167,507,640",
    link: "https://open.spotify.com/track/0NrtwAmRAdLxua31SzHvXr?si=fbbb88e198054e01",
  },
  {
    name: "The Glory",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:32",
    plays: "70,242,685",
    link: "https://open.spotify.com/track/0lWjRSzq5chA9fps3pM8Zr?si=82fc47acb7fd4c3d",
  },
  {
    name: "Homecoming",
    creator: "Kanye West, Chris Martin",
    albumCover: "../images/graduation album cover.png",
    timeLength: "2:18",
    plays: "8,026,989",
    link: "https://open.spotify.com/track/4iz9lGMjU1lXS51oPmUmTe?si=efb265525e964bdc",
  },
  {
    name: "Big Brother",
    creator: "Kanye West",
    albumCover: "../images/graduation album cover.png",
    timeLength: "4:47",
    plays: "55,413,052",
    link: "https://open.spotify.com/track/2L47m9erkB5KBZcaqWtYen?si=886a4d2b56644bce",
  },
  {
    name: "Good Night",
    creator: "Kanye West, Mos Def, Albe Back",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:05",
    plays: "23,913,843",
    link: "https://open.spotify.com/track/3bhyo2ED5Yd4RLydQBDtD6?si=b9fec1085b4b4052",
  },
];

export default songsArray;
