let songsArray = [
  {
    name: "Bitch dont kill my vibe",
    creator: "Kendrick Lamar",
    albumName: "good kid maad city",
    albumCover: "../images/good kid maad city album cover.png",
    timeLength: "5:10",
    inedex: "1",
    link: "https://open.spotify.com/track/0yhMmqax6HRAZxI7udEask?si=4b374b46646a4e52",
  },
  {
    name: "Me and Your Mama",
    creator: "Childish Gambino",
    albumName: '"Awaken, My Love"',
    albumCover: "../images/aweken my love album cover.png",
    timeLength: "6:19",
    inedex: "2",
    link: "https://open.spotify.com/track/4AFsRbaLKRWo3dDtjDFA2V?si=6320aacaf4d346c5",
  },
  {
    name: "Pink + White",
    creator: "Frank Ocean",
    albumName: "Blonde",
    albumCover: "../images/blond album cover.png",
    timeLength: "6:19",
    inedex: "3",
    link: "https://open.spotify.com/track/3xKsf9qdS1CyvXSMEid6g8?si=acfa9918f3ca4045",
  },
  {
    name: "Homecoming",
    creator: "Kanye West",
    albumName: "Graduation",
    albumCover: "../images/graduation album cover.png",
    timeLength: "3:23",
    inedex: "4",
    link: "https://open.spotify.com/track/4iz9lGMjU1lXS51oPmUmTe?si=74c5779bee5b462d",
  },
  {
    name: "2z Don Corleon",
    creator: "Lil 2z",
    albumName: "6AM",
    albumCover: "../images/6AM album cover.png",
    timeLength: "1:57",
    inedex: "5",
    link: "https://open.spotify.com/track/44xttcHOwxaQDVUOJO0vFe?si=6045ae8583e542fb",
  },
  {
    name: "Father Stretch My Hands Pt. 1",
    creator: "Kanye West",
    albumName: "The Life Of Pablo",
    albumCover: "../images/the life of pablo album cover.png",
    timeLength: "2:15",
    inedex: "6",
    link: "https://open.spotify.com/track/4KW1lqgSr8TKrvBII0Brf8?si=42b288b131954ee7",
  },
  {
    name: "Mary",
    creator: "Alex G",
    albumName: "Trick",
    albumCover: "../images/trick album cover.png",
    timeLength: "3:17",
    inedex: "7",
    link: "https://open.spotify.com/track/36TbBJ7mLPOZMAYs0p4mxb?si=4360522fcbeb470e",
  },
  {
    name: "Trance(with Travis Scott & Young Thug)",
    creator: "Metro Boomin, Travis Scott, Young Thug",
    albumName: "HEROES & VILLAINS",
    albumCover: "../images/heroes and villains album cover.png",
    timeLength: "3:14",
    inedex: "8",
    link: "https://open.spotify.com/track/5wG3HvLhF6Y5KTGlK0IW3J?si=855bc4acb27042fa",
  },
  {
    name: "Smack That",
    creator: "Akon, Eminem",
    albumName: "Konvicted",
    albumCover: "../images/konvicted album cover.png",
    timeLength: "3:32",
    inedex: "9",
    link: "https://open.spotify.com/track/2kQuhkFX7uSVepCD3h29g5?si=356f15bf611f4d24",
  },
  {
    name: "Runnin",
    creator: "21 Savage, Metro Boomin",
    albumName: "SAVAGE MODE II",
    albumCover: "../images/savage mode 2 album cover.png",
    timeLength: "3:15",
    inedex: "10",
    link: "https://open.spotify.com/track/5SWnsxjhdcEDc7LJjq9UHk?si=dd0d9cd0f1cd421f",
  },
];

export default songsArray;
